name: habido_app
description: Habido app

version: 1.0.5+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #api
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  http: ^0.13.3
  connectivity: ^3.0.6

  #utils
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.6
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  local_auth: ^1.1.6
  package_info_plus: ^1.0.4
  device_info: ^2.0.2
  simple_animations: ^3.1.1
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  permission_handler: ^8.1.4+2
  image_picker: ^0.8.3+2
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.1.1+1
  showcaseview: ^1.1.1
  audioplayers: ^0.20.1
  circular_reveal_animation: ^2.0.0

  #widgets
  smooth_page_indicator: ^0.3.0-nullsafety.0
  code_input: ^2.0.0
  carousel_slider: ^4.0.0
  percent_indicator: ^3.0.1
  flutter_slidable: ^0.6.0
  table_calendar: ^3.0.2
  badges: ^2.0.1
  fl_chart: ^0.40.0
  flutter_countdown_timer: ^4.1.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0 #flutter pub run flutter_launcher_icons:main

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher/launcher.png"
  image_path_android: "assets/images/launcher/launcher.png"
  adaptive_icon_background: "assets/images/launcher/launcher_background.png"
  adaptive_icon_foreground: "assets/images/launcher/launcher_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/launcher/
    - assets/images/global/
    - assets/images/intro/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/chat/
    - assets/images/test/
    - assets/images/habit/

  fonts:
    - family: Fira Sans Condensed
      fonts:
        - asset: assets/fonts/FiraSansCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/FiraSansCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/FiraSansCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraSansCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraSansCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSansCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/FiraSansCondensed-Black.ttf
          weight: 900
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900