name: habido_app
description: Habido app

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utils
  shared_preferences: ^2.0.6
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  simple_animations: ^3.1.1
  url_launcher: ^6.0.9

  #pattern
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3

  #widgets
  smooth_page_indicator: ^0.3.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0 #flutter pub run flutter_launcher_icons:main

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher/launcher.png"
  image_path_android: "assets/images/launcher/launcher.png"
  adaptive_icon_background: "assets/images/launcher/launcher_background.png"
  adaptive_icon_foreground: "assets/images/launcher/launcher_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/launcher/
    - assets/images/global/
    - assets/images/intro/
    - assets/images/login/

  fonts:
    - family: Fira Sans Condensed
      fonts:
        - asset: assets/fonts/FiraSansCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/FiraSansCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/FiraSansCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraSansCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraSansCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSansCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/FiraSansCondensed-Black.ttf
          weight: 900